AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for GitHub Actions (OIDC) in Shared Services Account for S3 and SNS access

Parameters:
  GitHubOrg:
    Type: String
    Description: GitHub organization name

  GitHubRepo:
    Type: String
    Description: GitHub repository name

  OIDCProviderArn:
    Type: String
    Description: ARN of GitHub OIDC provider (arn:aws:iam::<account-id>:oidc-provider/token.actions.githubusercontent.com)

  S3BucketName:
    Type: String
    Description: Name of S3 bucket for Terraform backend

Resources:
  GitHubActionsOIDCRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHubActionsOIDCRole-S3-SNS-ShS
      Description: Role for GitHub Actions to manage S3 and SNS in Shared Services account
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref OIDCProviderArn
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub "repo:${GitHubOrg}/${GitHubRepo}:*"

      Policies:
        - PolicyName: ManageSNSandS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: ManageS3
                Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                  - s3:GetBucketVersioning
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                  - s3:PutBucketTagging
                  - s3:GetEncryptionConfiguration
                Resource:
                  - !Sub "arn:aws:s3:::${S3BucketName}"
                  - !Sub "arn:aws:s3:::${S3BucketName}/*"

              - Sid: SNSTopicAccess
                Effect: Allow
                Action:
                  - sns:ListTopics
                  - sns:CreateTopic
                  - sns:DeleteTopic
                  - sns:GetTopicAttributes
                  - sns:SetTopicAttributes
                  - sns:Subscribe
                  - sns:Unsubscribe
                  - sns:Publish
                  - sns:TagResource
                  - sns:UntagResource
                  - sns:ListTagsForResource
                Resource: "*"

Outputs:
  GitHubActionsOIDCRoleArn:
    Description: ARN of the created GitHubActionsOIDCRole
    Value: !GetAtt GitHubActionsOIDCRole.Arn